name: Validate .NET solution
on:  
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate-dotnet:
    name: Validate .NET solution
    uses: azure-samples/code-validation/.github/workflows/dotnet.yml@main
    with:
      version: '8.0'
