name: Validate .NET code samples
on: pull_request
jobs:
  validate-dotnet:
    name: Validate .NET project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
      - name: Check .NET version
        run: dotnet --version       
      - name: Build .NET project
        run: dotnet build
      - name: Check .NET code format
        run: dotnet format --verify-no-changes